### ISSUE TITLE
Users permissions management

### ISSUE THREAD

**Issue by seuf** [seuf/imagize#1]
## Description

Allow or deny access to folders per user.
## Admin

Create a super user who can admin other users credentials and permissions per users.
in config.ini, add add a field 

```
admin_user=<admin>
```

Then if the user connected is equal to the admin user, add an "admin" menu / page to manage credential per folder.
## Config Storage

use a yaml or json serialised file to store permissions per users.
create a directory "config/users" where each user will have a permissions config file.
for example with foo.yml 

```

---
permissions:
  - folder1:
    access: True
    upload: False
  - folder2:
    access: True
    subdirs:
      - subfolder1:
        access: False
      - subfolder2:
        access: True
        upload: True
```

Then when a user want to access a directory we just have to check access for this path in the user's permissions file.
If a new folder is created, the default permission should be the parent folder permission.
